# Generated by Django 2.2.2 on 2019-08-29 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='nombre',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        unique=True,
                        verbose_name='slug',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        verbose_name='descripción',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='owner_classrooms',
                        to=settings.AUTH_USER_MODEL, verbose_name='dueño',
                    ),
                ),
            ],
        ),
    ]
